version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: chatdb_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: chatdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - chat-network

  redis:
    image: redis:7-alpine
    container_name: chat_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chat-network

  backend:
    build: ./be
    container_name: chat_backend
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/chatdb?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3001"
    volumes:
      - ./be:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - chat-network

  frontend:
    build: ./fe
    container_name: chat_frontend
    restart: always
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 